import time
from selenium import webdriver
from selenium.webdriver.support.select import Select
PATH="E:\drive\chromedriver"
driver=webdriver.Chrome(PATH)
driver.get("https://www.thesparksfoundationsingapore.org/")
driver.maximize_window()

print("test case 1")
if driver.title:
    title=driver.title
    print("website have the title:",title)
else:
    print("website did not have the title")
print("*" * 20)
print("test case 2")
print("*" * 20)
try:
    driver.find_element_by_xpath('//*[@id="home"]/div/div[1]/h1/a/*').click()
    print("logo is succesfully founded")
except:
       print("logo is not founded founded")
print("*" * 20)
print("test case 3")
print("*" * 20)
try:
    driver.find_element_by_class_name("navbar")
    print("nav bar verified")
except:
    print("nav bar not-verified")
print("*" * 20)
print("test case 4")
print("*" * 20)
try:
    driver.find_element_by_link_text("About Us").click()
    print(" Entering into About Us ")
    time.sleep(4)
    driver.find_element_by_link_text("Vision, Mission and Values").click()
    print(" Vision, Mission and Values page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Guiding Principles").click()
    print(" Guiding Principles page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Advisors and Patrons").click()
    print(" Advisors and Patrons page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Executive Team").click()
    print(" Executive Team page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Corporate Partners").click()
    print(" Corporate Partners page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Expert Mentors").click()
    print(" Expert Mentors page is working ")
    time.sleep(4)
    print("About us verified")
    time.sleep(4)
except:
    print("About Us not-verified")
print("*" * 20)
print("test case 5")
print("*" * 20)
try:
    (driver.find_element_by_partial_link_text("Policies").click())
    print(" Entering into Policies ")
    time.sleep(4)
    (driver.find_element_by_partial_link_text("Code of Ethics and Conduct").click())
    print(" Code of Ethics and Conduct page is working ")
    time.sleep(4)
    (driver.find_element_by_partial_link_text("Personal Data Policy").click())
    print(" Personal Data Policy page is working ")
    time.sleep(4)
    (driver.find_element_by_partial_link_text("Whistle Blowing Policy").click())
    print(" Whistle Blowing Policy page is working ")
    time.sleep(4)
    (driver.find_element_by_partial_link_text("Service Quality Values").click())
    print(" Service Quality Values page is working ")
    time.sleep(4)
    print("Policies verified")
    time.sleep(4)
except:
    print("Policies Not-verified")
print("*" * 20)
print("test case 6")
print("*" * 20)
try:
    driver.find_element_by_link_text("Programs").click()
    print(" Entering into Programs ")
    time.sleep(4)
    driver.find_element_by_link_text("Student Scholarship Program").click()
    print(" Student Scholarship Program page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Student Mentorship Program").click()
    print(" Student Mentorship Program page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Student SOS Program").click()
    print(" Student SOS Program page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Workshops").click()
    print(" Workshops page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Corporate Programs").click()
    print(" Corporate Programs page is working ")
    time.sleep(4)
    print("Programs verified")
    time.sleep(4)
except:
    print("Programs Not-verified")
print("*" * 20)
print("test case 7")
print("*" * 20)
try:
    driver.find_element_by_link_text("LINKS").click()
    print(" Entering into LINKS ")
    time.sleep(4)
    driver.find_element_by_link_text("Software & App").click()
    print(" Software & App page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Salient Features").click()
    print(" Salient Features page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("AI in Education").click()
    print(" AI in Education page is working ")
    time.sleep(4)
    print("LINKS verified")
    time.sleep(4)
except:
    print("LINKS not-verified")
print("*" * 20)
print("test case 8")
print("*" * 20)
try:
    driver.find_element_by_link_text("Contact Us").click()
    print(" Entering into Contact Us ")
    time.sleep(4)
    print("Contact Us verified")
    time.sleep(4)
except:
    print("Contact Us Not-verified")
print("*" * 20)
print("test case 9")
print("*" * 20)
try:
    driver.find_element_by_link_text("Join Us").click()
    print(" Entering into Join Us ")
    time.sleep(4)
    driver.find_element_by_link_text("Why Join Us").click()
    print(" Why Join Us page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Expert Mentor").click()
    print(" Expert Mentor page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Events Volunteer").click()
    print(" Events Volunteer page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Management Volunteer").click()
    print(" Management Volunteer page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Internship Positions").click()
    print(" Internship Positions page is working ")
    time.sleep(4)
    driver.find_element_by_link_text("Brand Ambassador").click()
    print(" Brand Ambassador page is working ")
    time.sleep(4)
    print("Join Us verified")
    time.sleep(2)
except:
    print("Join Us not-verified")
print("*" * 20)
print("test case 10")
print("*" * 20)
try:
    driver.find_element_by_link_text("Join Us").click()
    print(" Going to verify the form ")
    driver.find_element_by_link_text("Why Join Us").click()
    time.sleep(5)
    driver.find_element_by_name("Name").send_keys("RAGUL")
    time.sleep(5)
    driver.find_element_by_name("Email").send_keys("ragulraghavan75066@gmail.com")
    time.sleep(5)
    a = Select(driver.find_element_by_class_name("form-control"))
    a.select_by_visible_text("Intern")
    time.sleep(5)
    driver.find_element_by_class_name("button-w3layouts").click()
    time.sleep(5)
    print("join us form is working")

except:
    print("join us form is not working")
time.sleep(5)
print("*" * 20)
driver.quit()
